/** Floating worktree-window and review-panel styles. */
export const worktreeStyles = `
.uvf_root{position:fixed;inset:0;z-index:1200;pointer-events:none}
.uvf_win{--uvf-accent:#5b6cff;--uvf-positive:#20a66a;pointer-events:auto;position:fixed;isolation:isolate;display:flex;flex-direction:column;min-width:1px;min-height:1px;overflow:hidden;color:var(--dsw-alias-label-primary,#172033);background:var(--dsw-alias-bg-base,#fff);border:1px solid var(--dsw-alias-border-l2,#dfe3eb);border-radius:16px;box-shadow:0 1px 2px rgba(13,22,38,.08),0 18px 48px rgba(13,22,38,.2),0 0 0 1px rgba(255,255,255,.4) inset;transition:border-color .16s ease,box-shadow .16s ease}
.uvf_win:hover{border-color:color-mix(in srgb,var(--uvf-accent) 28%,var(--dsw-alias-border-l2,#dfe3eb));box-shadow:0 2px 5px rgba(13,22,38,.1),0 22px 58px rgba(13,22,38,.24),0 0 0 1px rgba(255,255,255,.5) inset}
.uvf_win[data-interaction]{transition:none;user-select:none}
.uvf_win[data-interaction]::after{content:"";position:absolute;inset:0;z-index:18;background:transparent}
.uvf_win_folded{height:48px!important}
.uvf_win_max{inset:12px!important;width:auto!important;height:auto!important;border-radius:18px;z-index:1300}
.uvf_windowHeader{position:relative;z-index:10;display:flex;align-items:center;gap:10px;height:48px;padding:0 8px 0 10px;flex:none;cursor:grab;touch-action:none;user-select:none;background:#f7f8fb;background:linear-gradient(180deg,color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 96%,#7583ff),color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 92%,#dfe3f5));border-bottom:1px solid color-mix(in srgb,var(--dsw-alias-border-l2,#dfe3eb) 78%,transparent)}
.uvf_win[data-interaction=move] .uvf_windowHeader{cursor:grabbing}.uvf_win_max .uvf_windowHeader{cursor:default}.uvf_win_folded .uvf_windowHeader{border-bottom:0}
.uvf_windowGlyph{display:grid;place-items:center;width:30px;height:30px;flex:none;border-radius:9px;color:#fff;background:linear-gradient(145deg,#7a87ff,#4f5fe7);box-shadow:0 5px 12px rgba(79,95,231,.25)}
.uvf_windowGlyph svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}
.uvf_windowIdentity{display:flex;flex-direction:column;justify-content:center;min-width:0;flex:1;line-height:1.2}
.uvf_windowTitle,.uvf_windowFile{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.uvf_windowTitle{font-size:12.5px;font-weight:650;letter-spacing:.01em;color:var(--dsw-alias-label-primary,#172033)}.uvf_windowFile{margin-top:2px;font-size:10.5px;color:var(--dsw-alias-label-tertiary,#7d8798)}
.uvf_chip{display:inline-flex;align-items:center;gap:6px;flex:none;padding:3px 8px;border:1px solid var(--dsw-alias-border-l2,#dfe3eb);border-radius:999px;font-size:10.5px;font-weight:600;line-height:16px;color:var(--dsw-alias-label-secondary,#566174);background:color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 75%,transparent)}
.uvf_pulse,.uvf_dot{position:relative;width:7px;height:7px;border-radius:50%;background:var(--uvf-positive);flex:none}.uvf_pulse::after{content:"";position:absolute;inset:-3px;border-radius:50%;border:1px solid currentColor;opacity:.24;animation:uvf-pulse 2s ease-out infinite}.uvf_chip[data-status=ready]{color:#16784d;border-color:color-mix(in srgb,#20a66a 30%,var(--dsw-alias-border-l2,#dfe3eb));background:color-mix(in srgb,#20a66a 8%,var(--dsw-alias-bg-base,#fff))}.uvf_chip[data-status=draft]{color:#9a6114;border-color:color-mix(in srgb,#d78b25 34%,var(--dsw-alias-border-l2,#dfe3eb));background:color-mix(in srgb,#d78b25 9%,var(--dsw-alias-bg-base,#fff))}.uvf_chip[data-status=draft] .uvf_pulse{background:#d78b25}
@keyframes uvf-pulse{0%{transform:scale(.7);opacity:.35}70%,100%{transform:scale(1.65);opacity:0}}
.uvf_windowControls{display:flex;align-items:center;gap:3px;flex:none}.uvf_windowControl{display:grid;place-items:center;width:28px;height:28px;padding:0;border:0;border-radius:8px;color:var(--dsw-alias-label-secondary,#566174);background:transparent;cursor:pointer;transition:color .12s ease,background .12s ease,transform .12s ease}.uvf_windowControl:hover{color:var(--dsw-alias-label-primary,#172033);background:color-mix(in srgb,var(--dsw-alias-label-primary,#172033) 8%,transparent)}.uvf_windowControl:active{transform:scale(.92)}.uvf_windowControl:focus-visible{outline:2px solid color-mix(in srgb,var(--uvf-accent) 65%,transparent);outline-offset:1px}.uvf_windowControl_danger:hover{color:#d94242;background:rgba(217,66,66,.1)}.uvf_windowControl svg{width:15px;height:15px;fill:none;stroke:currentColor;stroke-width:1.4;stroke-linecap:round;stroke-linejoin:round}
.uvf_windowBody{display:flex;flex:1;min-width:0;min-height:0;flex-direction:column;background:var(--dsw-alias-bg-base,#fff)}.uvf_windowBody[hidden]{display:none}
.uvf_units{display:flex;align-items:center;gap:5px;min-height:36px;padding:5px 9px;border-bottom:1px solid var(--dsw-alias-border-l2,#dfe3eb);overflow-x:auto;scrollbar-width:thin;background:color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 94%,#edf0f8)}
.uvf_unit{display:inline-flex;align-items:center;gap:4px;flex:none;max-width:220px;border:1px solid var(--dsw-alias-border-l2,#dfe3eb);border-radius:8px;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-secondary,#566174);font:11px/20px inherit;padding:0 9px;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;transition:border-color .12s ease,color .12s ease,background .12s ease}.uvf_unit:hover{border-color:color-mix(in srgb,var(--uvf-accent) 35%,var(--dsw-alias-border-l2,#dfe3eb));color:var(--dsw-alias-label-primary,#172033)}.uvf_unit_on{border-color:color-mix(in srgb,var(--uvf-accent) 55%,var(--dsw-alias-border-l2,#dfe3eb));color:#4554d6;background:color-mix(in srgb,var(--uvf-accent) 9%,var(--dsw-alias-bg-base,#fff));box-shadow:0 0 0 1px color-mix(in srgb,var(--uvf-accent) 10%,transparent) inset}.uvf_unit_icon{font-size:10px;opacity:.82}
.uvf_viewerShell{position:relative;display:flex;flex:1;min-width:0;min-height:0;background:#f1f3f7}.uvf_frame{display:block;flex:1;min-width:0;min-height:0;width:100%;height:100%;border:0;background:var(--dsw-alias-bg-base,#fff)}
.uvf_note{display:flex;flex:1;flex-direction:column;align-items:center;justify-content:center;gap:12px;padding:28px;text-align:center;font-size:12px;color:var(--dsw-alias-label-tertiary,#7d8798)}.uvf_note button{border:1px solid color-mix(in srgb,var(--uvf-accent) 40%,var(--dsw-alias-border-l2,#dfe3eb));border-radius:8px;padding:6px 13px;color:#fff;background:var(--uvf-accent);font:12px/18px inherit;cursor:pointer}
.uvf_resizeHandle{position:absolute;z-index:20;display:block;touch-action:none}.uvf_resize_n,.uvf_resize_s{left:16px;right:16px;height:10px;cursor:ns-resize}.uvf_resize_n{top:0}.uvf_resize_s{bottom:0}.uvf_resize_w,.uvf_resize_e{top:16px;bottom:16px;width:10px;cursor:ew-resize}.uvf_resize_w{left:0}.uvf_resize_e{right:0}.uvf_resize_nw,.uvf_resize_ne,.uvf_resize_sw,.uvf_resize_se{width:18px;height:18px}.uvf_resize_nw{left:0;top:0;cursor:nwse-resize}.uvf_resize_ne{right:0;top:0;cursor:nesw-resize}.uvf_resize_sw{left:0;bottom:0;cursor:nesw-resize}.uvf_resize_se{right:0;bottom:0;cursor:nwse-resize}.uvf_resize_se::after{content:"";position:absolute;right:4px;bottom:4px;width:7px;height:7px;border-right:1.5px solid color-mix(in srgb,var(--dsw-alias-label-tertiary,#7d8798) 58%,transparent);border-bottom:1.5px solid color-mix(in srgb,var(--dsw-alias-label-tertiary,#7d8798) 58%,transparent);border-radius:0 0 2px}
.uvf_panel{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-base);border-radius:12px;margin:8px auto 4px;max-width:900px;width:100%;overflow:hidden}.uvf_panelHead,.uvf_panelFoot{display:flex;align-items:center;gap:8px;padding:8px 12px}.uvf_panelHead{cursor:pointer}.uvf_panelTitle{flex:1;min-width:0;color:var(--dsw-alias-label-primary);font-size:13px;font-weight:600}.uvf_panelChip{font-size:11px;border-radius:999px;padding:1px 8px;background:var(--dsw-alias-interactive-bg-subtle)}.uvf_panelFrame{width:100%;height:440px;border:0}.uvf_panelFoot{border-top:1px solid var(--dsw-alias-border-l2)}.uvf_hint,.uvf_error{flex:1;font-size:12px;color:var(--dsw-alias-label-tertiary)}.uvf_error{color:#c0392b}.uvf_action{font:12px/18px inherit;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:4px 14px;cursor:pointer;background:var(--dsw-alias-interactive-bg-subtle)}.uvf_action[data-kind=merge],.uvf_action[data-kind=ready]{background:#1a7f4b;border-color:#1a7f4b;color:#fff}.uvf_action:disabled{opacity:.55}.uvf_btn{width:22px;height:22px;border:0;border-radius:6px;background:var(--dsw-alias-interactive-bg-subtle);color:var(--dsw-alias-label-secondary);cursor:pointer}
@media (prefers-reduced-motion:reduce){.uvf_win,.uvf_windowControl,.uvf_unit{transition:none}.uvf_pulse::after{animation:none}}
`
